name: Manual Trigger

on:
  repository_dispatch:
    types: [manual-trigger]
  workflow_dispatch:

jobs:
  manual-trigger:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run trigger script
        run: |
          python scripts/github/github_trigger.py
